### ISSUE TITLE
Interest in using Serverless framework for Lambda function

### ISSUE THREAD

**Issue by grocky** [tartanguru/alexa-assistant#34]
Hi @tartanguru. Do you have any interest in converting this project into a [serverless](https://serverless.com/) project? I deployed my lambda function with it recently and it cuts out some manual steps needed to get things up and running. 

If you're interested, I can clean things up in my fork and submit a PR.

**Comment by tartanguru** [comment]
Hi,

I must admit I don’t really know much about serverless. More than happy for
you to submit a PR as I’d be interested in seeing how it works

Thanks

**Comment by chriotte** [comment]
Hi,

+1 for this, converting the project into Serverless makes deploying into AWS a "one step" problem.

**Comment by tartanguru** [comment]
By Serverless are you refering to using Cloudformation?
If this is indeed the case then I am already working on deploying the version two release via cloudformation

**Comment by grocky** [comment]
Hey @tartanguru,

Sorry for the late reply here. I'll be glad to open a PR if you want to check it out.

[Serverless](https://serverless.com/) is a framework that helps to manage lambda functions. It does create a cloudformation stack and provides tools to manage the lambda function from the cli.

**Comment by tartanguru** [comment]
Hey Grocky,

I appreciate the PR and it certainly makes the deployment for developers much easier, however the big issue that I have is that 99% of the people installing this skill are not developers and based upon the tens of emails and support requests I get each week, the concept of getting them to use the command line, let alone install node, do an npm build and use other tools other than a web browser is going to be far beyond them. They *might* be able to cope with a cloud formation deploy though which I did toy with originally.

I don’t want to diminish your work in any way, but I have got to be realistic about what is achievable by the bulk of users.

On a related note - how does serverless deal with the fact that some of the node modules are native and need to be built on 64bit Linux (e.g. node-lame and grpc)? This was one of the reasons for include the node-modules folder. I was thinking of just moving these to a lib folder for realease 2 to make the download smaller

**Comment by grocky** [comment]
@tartanguru I completely understand! I forget where I read you say this before, but I making the deployment easy for non-developers is important to making this project successful and useful to a wider audience.

How would you feel about hosting the zip file elsewhere? In this way it'll be available to users if they just want to upload it themselves to the lambda function. The serverless framework generates a zip file that it uploads to AWS during deployment so whenever changes are made you can update the hosted file after verifying everything works. I was thinking it could be hosted in S3 with an open policy.

The native node modules are the one piece that isn't implemented in this PR. I was thinking the same as you to move those to a lib folder. There's a plugin that allows you to include other dependencies like those.

**Comment by tartanguru** [comment]
I actually did quite a bit of work on a Cloudformation config for the skill before it was originally released. The issue was the hosting of the zip file. Given the number of users of the skill (which from the github stats I estimate to be in the thousands), it wouldn't take long before I would have exceeded my monthly free S3 bandwidth limits and it would start costing me to host the skill. I could host the zip on my own web server but this wouldn't be usable from Cloudformation. Let ,e give this a little more thought

**Comment by tartanguru** [comment]
Ok,

Looked at this a little bit more and assuming that the cloudformation is created within the same AWS region as the S3 bucket then I won't incur any data transfer charges. I've added a mapping to the cloudformation script so that it looks up the correct region and then downloads from an s3 bucket in the same region

**Comment by tartanguru** [comment]
The latest version of the skill is now using a hosted cloud formation template for deployment - thanks for all the suggestions. I have moved this out of this project into this one so that I can use a different licence to prevent commercial use of my template and S3 resources.

https://github.com/tartanguru/alexa-assistant-instructions
