### ISSUE TITLE
Deal with IFTTT text responses

### ISSUE THREAD

**Issue by tartanguru** [tartanguru/alexa-assistant#6]
Need to deal with IFTTT responses

**Comment by rkm82** [comment]
Hi Ross, I have no idea how to contact you otherwise so - 

thanks for the great work. I saw that other than your previous google search skill, this one is not available in German. As I would need (or better - would love to have....) this in German, I was wondering whether there is anything I can do to support this - I have 0 coding experience, but I could provide translations from English <> German etc.?

Let me know if there's anything I can do in support to make this happen :)

Cheers from Switzerland
Rob

**Comment by tartanguru** [comment]
Hi Rob,

The Google Assistant API only supports US English at the moment, so other
than a couple of error messages, there isn't much support that the skill
can add for other languages.
Google has announced support for UK English, French and German later in the
year so I will update it to support these languages once they are available

Ross

**Comment by rkm82** [comment]
Hi Ross

 

Wow, thanks a lot for the super fast reply.

Well, seems like nothing else can be done here in that case… I’ll follow the project and hope that google supports this soon.

 

Thank you so much for making this whole thing happen :) People like you make this world a better place. (Seriously). 

Do you have any donation page or anything?

 

In the meanwhile – I’ve installed your “old” alexa-google-search. It seems to work perfectly, the only problem that I have is a funny little thing it gets wrong: 

 

When I ask google for, let’s say: 

 

“opening hours harrods”

 

The answer will be “harrods”. 

 

I was quite confused in the beginning as this was a *consistently* wrong behavior, but then I realized what happens is that the answer is always the “heading” of the info box on the right hand side of the search results.

It basically, instead of reading the search result, it reads the box header.

 

Would there be any quick fix to this, I think a lot of German users would be happy to still use the old version until the assistant / google api has been translated to German? 

 

Thanks so much

Cheers

 

Rob

 

 

Von: Ross Atkin [mailto:notifications@github.com] 
Gesendet: Freitag, 1. September 2017 12:47
An: tartanguru/alexa-assistant <alexa-assistant@noreply.github.com>
Cc: rkm82 <github@maciejewski.ch>; Comment <comment@noreply.github.com>
Betreff: Re: [tartanguru/alexa-assistant] Deal with IFTTT text responses (#6)

 

Hi Rob,

The Google Assistant API only supports US English at the moment, so other
than a couple of error messages, there isn't much support that the skill
can add for other languages.
Google has announced support for UK English, French and German later in the
year so I will update it to support these languages once they are available

Ross

**Comment by tartanguru** [comment]
Hi Rob,

I don't support the old skill anymore, as it was becoming quite hard to
make sure that it worked with all of the variations and was taking up a
huge amount of my time as it is basically just a hack.

I did create a version that dealt with store opening times. You might want
to try this instead - just upload the new Archive.zip from this branch:-

https://github.com/tartanguru/alexa-google-search/tree/Version-2-final

Let me know if this works for you

Ross

**Comment by tartanguru** [comment]
Closing issue as beta support text responses
